main: com.cavetale.pvparena.PVPArenaPlugin

name: PVPArena
version: 0.1
description: PVPArena Plugin
api-version: 1.13

author: StarTux
website: https://github.com/StarTux/PVPArena

depend: [Sidebar]
softdepend: []

commands:

  pvparena:
    aliases: [pvp]
    description: PVPArena Command
    permission: pvparena.pvparena
    usage: |-
      /pvparena

permissions:

  pvparena.pvparena:
    description: Use /pvparena
    default: op
