main: com.cavetale.pvparena.PVPArenaPlugin

name: PVPArena
version: 0.1
description: PVPArena Plugin
api-version: 1.13

author: StarTux
website: https://github.com/StarTux/PVPArena

depend: [Sidebar, AFK]
softdepend: []

commands:

  spectator:
    aliases: [spectate, spec]
    description: Toggle spectator mode
    permission: pvparena.player
    usage: |-
      /spec - Toggle spectator mode

  pvparena:
    aliases: [pvp]
    description: PVPArena Command
    permission: pvparena.pvparena
    usage: |-
      /pvparena

permissions:

  pvparena.player:
    description: Play the game
    default: op

  pvparena.pvparena:
    description: Use /pvparena
    default: op
