main: com.cavetale.pvparena.PVPArenaPlugin
name: PVPArena

version: 0.1
api-version: 1.19

description: PVPArena Plugin
author: StarTux
website: https://github.com/StarTux/PVPArena

depend: [Core, Mytems, Fam, Title, Server, AFK]
softdepend: []

commands:

  spectator:
    aliases: [spectate, spec]
    description: Toggle spectator mode
    permission: pvparena.pvparena
    usage: |-
      /spec - Toggle spectator mode

  pvpadmin:
    aliases: [pvpadm]
    description: Admin Command
    permission: pvparena.admin
    usage: |-
      /pvparena start
      /pvparena stop
      /pvparena save
      /pvparena load
      /pvparena rule <rule> - Enable special rule
      /pvparena nextworld <worldname> - Load any world next
      /pvparena skip - Force skip current world next round
      /pvparena areas - Dump current areas file
      /pvparena event - Toggle event mode
      /pvparena score - Score commands

permissions:

  pvparena.pvparena:
    description: Use /pvparena
    default: op

  pvparena.admin:
    description: Use /pvpadmin
    default: op
