main: com.cavetale.pvparena.PVPArenaPlugin
name: PVPArena

version: 0.1
api-version: '1.21.8'

description: PVPArena Plugin
author: StarTux
website: https://github.com/StarTux/PVPArena

depend:
- Core
- Mytems
- Fam
- Title
- Server
- AFK
- Creative
- Area
softdepend: []

commands:

  spectator:
    aliases: [spectate, spec]
    description: Toggle spectator mode
    permission: pvparena.pvparena
    usage: |-
      /spec - Toggle spectator mode

  pvparena:
    aliases: []
    description: Player command
    permission: pvparena.pvparena
    usage: |-
      /pvparena vote

  pvpadmin:
    aliases: [pvpadm]
    description: Admin Command
    permission: pvparena.admin
    usage: |-
      /pvpadm start
      /pvpadm stop
      /pvpadm save
      /pvpadm load
      /pvpadm rule <rule> - Enable special rule
      /pvpadm nextworld <worldname> - Load any world next
      /pvpadm skip - Force skip current world next round
      /pvpadm areas - Dump current areas file
      /pvpadm event - Toggle event mode
      /pvpadm score - Score commands

permissions:

  pvparena.pvparena:
    description: Use /pvparena
    default: op

  pvparena.admin:
    description: Use /pvpadmin
    default: op
